from ctypes.wintypes import PUSHORT

SCALE = 4
FPS = 60
SPEED = 1

NATIVE_WIDTH = 240
NATIVE_HEIGHT = 160
NATIVE_SIZE = (NATIVE_WIDTH, NATIVE_HEIGHT)

DISPLAY_WIDTH = NATIVE_WIDTH*SCALE
DISPLAY_HEIGHT = NATIVE_HEIGHT*SCALE
DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)

TOP_LEFT = (0, 0)

CHARACTER_WIDTH = 14
CHARACTER_HEIGHT = 20
CHARACTER_SIZE = (CHARACTER_WIDTH, CHARACTER_HEIGHT)
CHARACTER_SCREEN_CENTER_WIDTH = NATIVE_WIDTH/2 - CHARACTER_WIDTH/2
CHARACTER_SCREEN_CENTER_HEIGHT = NATIVE_HEIGHT/2 - CHARACTER_HEIGHT/2

MAIN_SCREEN = "MAIN_SCREEN"
INSIDE_SCREEN = "INSIDE_SCREEN"
SECOND_INSIDE_SCREEN = "SECOND_INSIDE_SCREEN"

UP = "UP"
DOWN = "DOWN"
LEFT = "LEFT"
RIGHT = "RIGHT"
STOP = "STOP"

MOVE_TRANSLATE = {UP: (0,-1),
                  DOWN: (0,1),
                  LEFT: (-1,0),
                  RIGHT: (1,0),
                  STOP: (0,0)}

# ACTIONS
PUSH = "PUSH"
POP = "POP"

STATIC_CAMERA = "STATIC_CAMERA"
MOVING_CAMERA = "MOVING_CAMERA"

BACKGROUND_LAYER = 0
BUILDINGS_LAYER = 1
PORTAL_LAYER = 2
CHARACTERS_LAYER = 3

BACKGROUND = "BACKGROUND"
BUILDING = "BUILDING"
PORTAL = "PORTAL"
CHARACTER = "CHARACTER"