SCALE = 4
FPS = 60
SPEED = 1

NATIVE_WIDTH = 240
NATIVE_HEIGHT = 160
NATIVE_SIZE = (NATIVE_WIDTH, NATIVE_HEIGHT)

DISPLAY_WIDTH = NATIVE_WIDTH*SCALE
DISPLAY_HEIGHT = NATIVE_HEIGHT*SCALE
DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)

TOP_LEFT = (0, 0)

CHARACTER_WIDTH = 14
CHARACTER_HEIGHT = 20
CHARACTER_SIZE = (CHARACTER_WIDTH, CHARACTER_HEIGHT)
CHARACTER_SCREEN_CENTER_WIDTH = NATIVE_WIDTH/2 - CHARACTER_WIDTH/2
CHARACTER_SCREEN_CENTER_HEIGHT = NATIVE_HEIGHT/2 - CHARACTER_HEIGHT/2

MAIN_SCREEN = "MAIN_SCREEN"

START_STATE = MAIN_SCREEN
