#MAIN VALUES
SCALE = 6
FPS = 60
SPEED = 1

# NATIVE SCREEN DIMENSIONS
NATIVE_WIDTH = 240
NATIVE_HEIGHT = 160
NATIVE_SIZE = (NATIVE_WIDTH, NATIVE_HEIGHT)

# SCALED SCREEN DIMENSIONS
DISPLAY_WIDTH = NATIVE_WIDTH*SCALE
DISPLAY_HEIGHT = NATIVE_HEIGHT*SCALE
DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)

# SCREEN ANCHOR POINTS
TOP_LEFT = (0, 0)

# CHARACTER DIMENSIONS
CHARACTER_WIDTH = 14
CHARACTER_HEIGHT = 20
CHARACTER_SIZE = (CHARACTER_WIDTH, CHARACTER_HEIGHT)
CHARACTER_SCREEN_CENTER_WIDTH = NATIVE_WIDTH/2 - CHARACTER_WIDTH/2
CHARACTER_SCREEN_CENTER_HEIGHT = NATIVE_HEIGHT/2 - CHARACTER_HEIGHT/2

# TILE SIZE
TILE_WIDTH = 16
TILE_HEIGHT = TILE_WIDTH
TILE_SIZE = (TILE_WIDTH, TILE_HEIGHT)

# GAME STATES
MAIN_SCREEN = "MAIN_SCREEN"
INSIDE_SCREEN = "INSIDE_SCREEN"
SECOND_INSIDE_SCREEN = "SECOND_INSIDE_SCREEN"

# GAME STATE TERRAIN LOAD DICTIONARY
STATE_DICT = {MAIN_SCREEN: "terrains/main_terrain.txt",
              INSIDE_SCREEN: "terrains/inside_terrain.txt",
              SECOND_INSIDE_SCREEN: "terrains/second_inside_terrain.txt"}

# MOVEMENT DIRECTIONS
UP = "UP"
DOWN = "DOWN"
LEFT = "LEFT"
RIGHT = "RIGHT"
STOP = "STOP"
MOVE_TRANSLATE = {UP: (0,-1),
                  DOWN: (0,1),
                  LEFT: (-1,0),
                  RIGHT: (1,0),
                  STOP: (0,0)}

# ACTIONS
PUSH = "PUSH"
POP = "POP"

# CAMERA MODES
STATIC_CAMERA = "STATIC_CAMERA"
MOVING_CAMERA = "MOVING_CAMERA"

# LAYER INDEXES
BACKGROUND_LAYER = 0
BUILDINGS_LAYER = 1
BUILDING_FRONT_LAYER = 2
PORTAL_LAYER = 3
CHARACTERS_LAYER = 4

# ENTITIES NAMES
BACKGROUND = "BACKGROUND"
BUILDING = "BUILDING"
BUILDING_FRONT = "BUILDING_FRONT"
PORTAL = "PORTAL"
CHARACTER = "CHARACTER"

# GAME STATE CHANGE
NO_JUMP = "NO_JUMP"
REVERT_STATE = "REVERT_STATE"
JUMP_MODE = "JUMP_MODE"
BACK_MODE = "BACK_MODE"

# BUILDING NAMES
DMCS = ("DMCS")

#PORTAL OFFET

PORTAL_OFFSET = {DMCS: (5,4)}