#MAIN VALUES
SCALE = 5
FPS = 60
SPEED = 5

# NATIVE SCREEN DIMENSIONS
NATIVE_WIDTH = 240
NATIVE_HEIGHT = 160
NATIVE_SIZE = (NATIVE_WIDTH, NATIVE_HEIGHT)

# SCALED SCREEN DIMENSIONS
DISPLAY_WIDTH = NATIVE_WIDTH*SCALE
DISPLAY_HEIGHT = NATIVE_HEIGHT*SCALE
DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)

# SCREEN ANCHOR POINTS
TOP_LEFT = (0, 0)

# CHARACTER DIMENSIONS
CHARACTER_WIDTH = 14
CHARACTER_HEIGHT = 19
CHARACTER_SIZE = (CHARACTER_WIDTH, CHARACTER_HEIGHT)
CHARACTER_SCREEN_CENTER_WIDTH = NATIVE_WIDTH/2 - CHARACTER_WIDTH/2
CHARACTER_SCREEN_CENTER_HEIGHT = NATIVE_HEIGHT/2 - CHARACTER_HEIGHT/2

# TILE SIZE
TILE_WIDTH = 16
TILE_HEIGHT = TILE_WIDTH
TILE_SIZE = (TILE_WIDTH, TILE_HEIGHT)

# GAME STATES
MAIN_SCREEN = "MAIN_SCREEN"
INSIDE_SCREEN = "INSIDE_SCREEN"
SECOND_INSIDE_SCREEN = "SECOND_INSIDE_SCREEN"

# GAME STATE TERRAIN LOAD DICTIONARY
STATE_DICT = {MAIN_SCREEN: "engine/terrains/terrain.txt",
              INSIDE_SCREEN: "engine/terrains/inside_terrain.txt",
              SECOND_INSIDE_SCREEN: "engine/terrains/second_inside_terrain.txt"}

# MOVEMENT DIRECTIONS
UP = "UP"
DOWN = "DOWN"
LEFT = "LEFT"
RIGHT = "RIGHT"
STOP = "STOP"
MOVE_TRANSLATE = {UP: (0,-1),
                  DOWN: (0,1),
                  LEFT: (-1,0),
                  RIGHT: (1,0),
                  STOP: (0,0)}

# ACTIONS
PUSH = "PUSH"
POP = "POP"

# CAMERA MODES
STATIC_CAMERA = "STATIC_CAMERA"
MOVING_CAMERA = "MOVING_CAMERA"

# LAYER INDEXES
BACKGROUND_LAYER = 0
CHARACTERS_LAYER = 1
BUILDINGS_LAYER = 2
PORTAL_LAYER = 3
BUILDING_FRONT_LAYER = 4
FX_LAYER = 5

# ENTITIES NAMES
BACKGROUND = "BACKGROUND"
BUILDING = "BUILDING"
BUILDING_FRONT = "BUILDING_FRONT"
PORTAL = "PORTAL"
CHARACTER = "CHARACTER"
FX = "FX"

# GAME STATE CHANGE
NO_JUMP = "NO_JUMP"
REVERT_STATE = "REVERT_STATE"
JUMP_MODE = "JUMP_MODE"
BACK_MODE = "BACK_MODE"

# BUILDING NAMES
DMCS = "DMCS"
BIBLIOTEKA = "BIBLIOTEKA"
CJ = "CJ"
ZATOKASPORTU = "ZATOKASPORTU"
WOIZ = "WOIZ"
ARCH = "ARCH"
WFTIMS = "WFTIMS"
BLOCKADE = "BLOCKADE"

# BUILDING FILE NAMES DICTIONARY
BUILDING_FILE_DICTIONARY = {
    DMCS: ["engine/images/DMCS/DMCS_znacznik.png", "engine/images/DMCS/DMCS_budynek.png"],
    BIBLIOTEKA: ["engine/images/BIBLIOTEKA/BIBLIOTEKA_znacznik.png", "engine/images/BIBLIOTEKA/BIBLIOTEKA_budynek.png"],
    CJ: ["engine/images/CJ/CJ_znacznik.png", "engine/images/CJ/CJ_budynek.png"],
    ZATOKASPORTU: ["engine/images/ZATOKASPORTU/ZATOKASPORTU_znacznik.png", "engine/images/ZATOKASPORTU/ZATOKASPORTU_budynek.png"],
    WOIZ: ["engine/images/WOIZ/WOIZ_znacznik.png", "engine/images/WOIZ/WOIZ_budynek.png"],
    ARCH: ["engine/images/ARCH/ARCH_znacznik.png", "engine/images/ARCH/ARCH_budynek.png"],
    WFTIMS: ["engine/images/WFTIMS/WFTIMS_znacznik.png", "engine/images/WFTIMS/WFTIMS_budynek.png"]
}

#PORTAL OFFSET
PORTAL_OFFSET = {DMCS: (5,4, 2*TILE_WIDTH, 1*TILE_HEIGHT),
                 BIBLIOTEKA: (28, 2, 1*TILE_WIDTH, 2*TILE_HEIGHT),
                 CJ: (20, 3, 1*TILE_WIDTH, 2*TILE_HEIGHT),
                 ZATOKASPORTU: (None, None, None, None),
                 WOIZ: (0, 6, 1*TILE_WIDTH, 2*TILE_HEIGHT),
                 ARCH: (0, 1, 1*TILE_WIDTH, 2*TILE_HEIGHT),
                 WFTIMS: (10, 4, 2*TILE_WIDTH, 1*TILE_HEIGHT)}
